---

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  config:
    import: optional:configserver:http://configserver:8090/
management:
  endpoint:
    shutdown:
      enabled: true
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

