server:
    port: 8080
management:
    endpoint:
        shutdown:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
info:
    app:
        Description: PMU  Course Application
        name: Course Microservice
        version: 1.0.0
spring:
    datasource:
        password: '{cipher}c6f5efdeb26b003bfdb8608d9db613d5cfa2d870df3ceeaec64c77a64ecb992f'
        url: jdbc:mysql://coursedb/pmu_course?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        username: '{cipher}c6f5efdeb26b003bfdb8608d9db613d5cfa2d870df3ceeaec64c77a64ecb992f'
    jpa:
        databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
eureka :
    instance:
        app-name: course
        prefer-ip-address: true
    client:
        enabled: true
        registerWithEureka: true
        fetch-registry: true


        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/